apiVersion: v1
kind: Secret
metadata:
  namespace: monitoramento
  name: cloudopss-grafana
  labels:
    app.kubernetes.io/name: cloudopss
    app.kubernetes.io/component: grafana
type: Opaque
data:
  # By default, admin-user is set to `admin`
  admin-user: YWRtaW4=
  admin-password: cGFzc3dvcmQxMjM=