apiVersion: certmanager.k8s.io/v1alpha1  
kind: ClusterIssuer
metadata:
  name: acme-letsencrypt-production
  namespace: $NAMESPACE
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: $EMAIL
    privateKeySecretRef:
      name: $REF
    http01: {}